package formularios;

import clases.Datos;
import clases.Opcion;
import clases.Utilidades;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

public class frmFactura extends javax.swing.JInternalFrame {

    private DefaultTableModel miTabla;
     private Datos misDatos;

     
    public void setDatos(Datos d) {
        this.misDatos = d;
    }

    /**
     * Creates new form frmFactura
     */
    public frmFactura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnBuscarCliente = new javax.swing.JButton();
        btnBuscarProducto = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEliminarTodo = new javax.swing.JButton();
        btnGrabar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDetalle = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtTotalValor = new javax.swing.JTextField();
        txtTotalCantidad = new javax.swing.JTextField();
        cmbCliente = new javax.swing.JComboBox();
        cmbProducto = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        txtNumFactura = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Nueva Factura");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setText("Fecha:");

        txtFecha.setEnabled(false);
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });

        jLabel2.setText("Cliente *:");

        jLabel3.setText("Producto *:");

        btnBuscarCliente.setText("...");
        btnBuscarCliente.setToolTipText("Buscar un cliente");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        btnBuscarProducto.setText("...");
        btnBuscarProducto.setToolTipText("Buscar un producto");
        btnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductoActionPerformed(evt);
            }
        });

        jLabel4.setText("Cantidad *:");

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnAdicionar.setToolTipText("Agregar un producto");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/substract.png"))); // NOI18N
        btnEliminar.setToolTipText("Quitar un producto");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnEliminarTodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete_all.png"))); // NOI18N
        btnEliminarTodo.setToolTipText("Quitar todos los productos");
        btnEliminarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTodoActionPerformed(evt);
            }
        });

        btnGrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accept2.png"))); // NOI18N
        btnGrabar.setToolTipText("Graba la factura");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        tblDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDetalle.setEnabled(false);
        jScrollPane2.setViewportView(tblDetalle);

        jLabel5.setText("Totales:");

        txtTotalValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalValor.setEnabled(false);
        txtTotalValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalValorActionPerformed(evt);
            }
        });

        txtTotalCantidad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalCantidad.setEnabled(false);
        txtTotalCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalCantidadActionPerformed(evt);
            }
        });

        cmbCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cmbProducto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setText("Nº:");

        txtNumFactura.setEnabled(false);
        txtNumFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumFacturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAdicionar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminarTodo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGrabar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cmbCliente, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(223, 223, 223)
                                        .addComponent(jLabel6)
                                        .addGap(28, 28, 28)
                                        .addComponent(txtNumFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cmbProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBuscarCliente)
                                    .addComponent(btnBuscarProducto))))
                        .addGap(0, 60, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotalCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalValor, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtNumFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnBuscarCliente)
                    .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnBuscarProducto)
                    .addComponent(cmbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnAdicionar)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnEliminar)
                    .addComponent(btnEliminarTodo)
                    .addComponent(btnGrabar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        frmBusquedaCliente miBusqueda = new frmBusquedaCliente(null, closable);
        miBusqueda.setDatos(misDatos);
        //Centramos el formulario en la pantalla (no en ventana)
        miBusqueda.setLocationRelativeTo(null);
        miBusqueda.setVisible(true);
        //Capturamos el cliente seleccionado
        String respuesta = miBusqueda.getRespuesta();
        if (respuesta.equals("")) {
            return;
        }
        //Buscamos en el combobox el cliente devuelto
        for (int i = 0; i < cmbCliente.getItemCount(); i++) {
            if (((Opcion)cmbCliente.getItemAt(i)).getValor().equals(respuesta)) {
                cmbCliente.setSelectedIndex(i);
                return;
            }
        }
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
        frmBusquedaProducto miBusqueda = new frmBusquedaProducto(null, closable);
        miBusqueda.setDatos(misDatos);
        //Centramos el formulario en la pantalla (no en ventana)
        miBusqueda.setLocationRelativeTo(null);
        miBusqueda.setVisible(true);
        //Capturamos el cliente seleccionado
        String respuesta = miBusqueda.getRespuesta();
        if (respuesta.equals("")) {
            return;
        }
        for (int i = 0; i < cmbProducto.getItemCount(); i++) {
            if (((Opcion)cmbProducto.getItemAt(i)).getValor().equals(respuesta)) {
                cmbProducto.setSelectedIndex(i);
                return;
            }
        }
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtTotalValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalValorActionPerformed

    private void txtTotalCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalCantidadActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        try {
            //Establecemos el número de factura
            txtNumFactura.setText("0001-" + Utilidades.agregarCeros(""
                    + (misDatos.getNumFactura()), 8));
            
            //Cargamos los clientes
            Opcion opcion;
            opcion = new Opcion("NA", "Seleccione un cliente...");
            cmbCliente.addItem(opcion);
            ResultSet rs = misDatos.getClientes();
            
            while (rs.next()) {
                opcion = new Opcion(
                    rs.getString("idCliente"),
                    rs.getString("nombres") + " "
                    + rs.getString("apellidos"));
                
                cmbCliente.addItem(opcion);
            }
            
            //Cargamos los productos
            opcion = new Opcion("NA", "Seleccione un producto...");
            cmbProducto.addItem(opcion);
            ResultSet rs2 = misDatos.getProductos();
            
            while (rs2.next()) {
                opcion = new Opcion(
                        rs2.getString("idProducto"),
                        rs2.getString("descripcion"));
                
                cmbProducto.addItem(opcion);
            }
            
            txtFecha.setText(Utilidades.dateToString(new Date()));
            txtTotalCantidad.setText("0");
            txtTotalValor.setText("0");
            llenarTabla();
            
        } catch (SQLException ex) {
            Logger.getLogger(frmFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        try {
            if (cmbProducto.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(rootPane, "Seleccione un producto");
                cmbProducto.requestFocusInWindow();
                return;
            }
            if (txtCantidad.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane,
                        "Debe ingresar una cantidad");
                txtCantidad.requestFocusInWindow();
                return;
            }
            
            if (!Utilidades.isNumeric(txtCantidad.getText())) {
                JOptionPane.showMessageDialog(rootPane,
                        "Debe ingresar una cantidad numérica");
                txtCantidad.setText("");
                txtCantidad.requestFocusInWindow();
                return;
            }
            
            int cantidad = Integer.parseInt(txtCantidad.getText());
            
            if (cantidad <= 0) {
                JOptionPane.showMessageDialog(rootPane,
                        "Debe ingresar un valor mayor a cero");
                txtCantidad.setText("");
                txtCantidad.requestFocusInWindow();
                return;
            }
            
            //Buscamos los datos del producto seleccionado
            ResultSet rs = misDatos.getProducto(
                    ((Opcion) cmbProducto.getSelectedItem()).getValor());
            
            if (rs.next()) {
                //Adicionamos el producto a la tabla
                String registro[] = new String[5];
                int precio = rs.getInt("precio");
                int valor = precio * cantidad;
                registro[0] = rs.getString("idProducto");
                registro[1] = rs.getString("descripcion");
                registro[2] = "" + precio;
                registro[3] = "" + cantidad;
                registro[4] = "" + valor;
                miTabla.addRow(registro);
                cmbProducto.setSelectedIndex(0);
                txtCantidad.setText("");
                cmbProducto.requestFocusInWindow();
                //Actualizamos los totales
                totales();
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        if (cmbCliente.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Seleccione un cliente");
            cmbCliente.requestFocusInWindow();
            return;
        }

        int totalCantidad = Integer.parseInt(txtTotalCantidad.getText());
        if (totalCantidad == 0) {
            JOptionPane.showMessageDialog(rootPane,
                    "Debe ingresar detalle de la factura");
            cmbProducto.requestFocusInWindow();
            return;
        }

        int respuesta = JOptionPane.showConfirmDialog(rootPane,
                "¿Está seguro de grabar la factura?");
        if (respuesta != 0) {
            return;
        }

        //Grabamos la factura

            
        //Obtenemos el número de factura anterior
        int numFactura = misDatos.getNumFactura();

        //Grabamos el encabezado de la factura
        misDatos.agregarFactura(
                numFactura, 
                ((Opcion) cmbCliente.getSelectedItem()).getValor(), 
                Utilidades.stringToDate(txtFecha.getText()));

        //Grabamos el detalle de la factura
        int num = tblDetalle.getRowCount();
        //Por cada línea de detalle, grabamos una línea en la BD
        for (int i = 0; i < num; i++) {
            misDatos.agregarDetalleFactura(
                    numFactura,
                    i,
                    Utilidades.objectToString(tblDetalle.getValueAt(i, 0)),
                    Utilidades.objectToString(tblDetalle.getValueAt(i, 1)),
                    Utilidades.objectToInt(tblDetalle.getValueAt(i, 2)),
                    Utilidades.objectToInt(tblDetalle.getValueAt(i, 3)));
        }

        //Inicializamos los campos
        cmbCliente.setSelectedIndex(0);
        limpiarTabla();
        totales();
        cmbCliente.requestFocusInWindow();
        JOptionPane.showMessageDialog(rootPane,
                "Factura " + numFactura + " generada con éxito.");

        //Establecemos el número de factura para un nuevo ingreso
        txtNumFactura.setText("0001-" + Utilidades.agregarCeros("" 
                + (misDatos.getNumFactura()), 8));

    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnEliminarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTodoActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(rootPane,
                "¿Está seguro de borrar el detalle?");
        if (respuesta != 0) {
            return;
        }
        limpiarTabla();
        totales();
    }//GEN-LAST:event_btnEliminarTodoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (cmbProducto.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Seleccione un producto");
            cmbProducto.requestFocusInWindow();
            return;
        }

        try {
            DefaultTableModel modelo = (DefaultTableModel) tblDetalle.getModel();
            int filas = tblDetalle.getRowCount();
            for (int i = 0; filas > i; i++) {
                String idTabla = Utilidades.objectToString(tblDetalle.getValueAt(i, 0));
                String idCombo = ((Opcion) cmbProducto.getSelectedItem()).getValor();
                if (idTabla.equals(idCombo)) {
                    modelo.removeRow(i);
                    //Actualizamos los totales
                    totales();
                    return;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtNumFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumFacturaActionPerformed

    private void llenarTabla() {
        String titulos[] = {"ID Producto", "Descripción", "Precio", "Cantidad",
            "Valor"};
        String registro[] = new String[5];
        miTabla = new DefaultTableModel(null, titulos);
        tblDetalle.setModel(miTabla);

        //Alinear campos numéricos a la derecha
        DefaultTableCellRenderer dtcr = new DefaultTableCellRenderer();
        dtcr.setHorizontalAlignment(SwingConstants.RIGHT);
        tblDetalle.getColumnModel().getColumn(2).setCellRenderer(dtcr);
        tblDetalle.getColumnModel().getColumn(3).setCellRenderer(dtcr);
        tblDetalle.getColumnModel().getColumn(4).setCellRenderer(dtcr);
    }

    private void totales() {

        int sumaCantidad = 0;
        int sumaValor = 0;
        int num = tblDetalle.getRowCount();
        for (int i = 0; i < num; i++) {
            sumaCantidad += Utilidades.objectToInt(tblDetalle.getValueAt(i, 3));
            sumaValor += Utilidades.objectToInt(tblDetalle.getValueAt(i, 4));
        }
        txtTotalCantidad.setText("" + sumaCantidad);
        txtTotalValor.setText("" + sumaValor);
    }

    public void limpiarTabla() {
        try {
            DefaultTableModel modelo = (DefaultTableModel) tblDetalle.getModel();
            int filas = tblDetalle.getRowCount();
            for (int i = 0; filas > i; i++) {
                modelo.removeRow(0);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarTodo;
    private javax.swing.JButton btnGrabar;
    public javax.swing.JComboBox cmbCliente;
    public javax.swing.JComboBox cmbProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblDetalle;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNumFactura;
    private javax.swing.JTextField txtTotalCantidad;
    private javax.swing.JTextField txtTotalValor;
    // End of variables declaration//GEN-END:variables
}
