package formularios;

import clases.Datos;
import clases.Opcion;
import clases.Reporte;
import clases.Utilidades;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class frmReporteFacturas extends javax.swing.JInternalFrame {

    private Datos misDatos;

    public void setDatos(Datos d) {
        this.misDatos = d;
    }

    public frmReporteFacturas() {
        initComponents();

        //Agregar los botones para que sean excluyentes
        bgrFiltro.add(rbtTodo);
        bgrFiltro.add(rbtSeleccion);

        bgrTipo.add(rbtFecha);
        bgrTipo.add(rbtNroFactura);
        bgrTipo.add(rbtCliente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgrFiltro = new javax.swing.ButtonGroup();
        bgrTipo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtArchivo = new javax.swing.JTextField();
        btnSeleccionArchivo = new javax.swing.JButton();
        rbtFecha = new javax.swing.JRadioButton();
        rbtNroFactura = new javax.swing.JRadioButton();
        rbtCliente = new javax.swing.JRadioButton();
        rbtTodo = new javax.swing.JRadioButton();
        rbtSeleccion = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dchFechaInicial = new com.toedter.calendar.JDateChooser();
        dchFechaFinal = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        btnGenerarReporte = new javax.swing.JButton();
        cmbFacturaFinal = new javax.swing.JComboBox();
        cmbCliente = new javax.swing.JComboBox();
        cmbFacturaInicial = new javax.swing.JComboBox();

        setClosable(true);
        setIconifiable(true);
        setTitle("Reporte de Facturas");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setText("Archivo:");

        txtArchivo.setText("Reporte");

        btnSeleccionArchivo.setText("...");
        btnSeleccionArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionArchivoActionPerformed(evt);
            }
        });

        rbtFecha.setSelected(true);
        rbtFecha.setText("Fecha");
        rbtFecha.setEnabled(false);
        rbtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtFechaActionPerformed(evt);
            }
        });

        rbtNroFactura.setText("Nº Factura");
        rbtNroFactura.setEnabled(false);
        rbtNroFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtNroFacturaActionPerformed(evt);
            }
        });

        rbtCliente.setText("Cliente");
        rbtCliente.setEnabled(false);
        rbtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtClienteActionPerformed(evt);
            }
        });

        rbtTodo.setSelected(true);
        rbtTodo.setText("Todas");
        rbtTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtTodoActionPerformed(evt);
            }
        });

        rbtSeleccion.setText("Selección");
        rbtSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtSeleccionActionPerformed(evt);
            }
        });

        jLabel2.setText("Desde:");

        jLabel3.setText("Hasta:");

        dchFechaInicial.setEnabled(false);

        dchFechaFinal.setEnabled(false);

        jLabel4.setText("Desde:");

        jLabel5.setText("Hasta:");

        jLabel6.setText("Cliente:");

        btnGenerarReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/report2.png"))); // NOI18N
        btnGenerarReporte.setText("Generar reporte");
        btnGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReporteActionPerformed(evt);
            }
        });

        cmbFacturaFinal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbFacturaFinal.setEnabled(false);
        cmbFacturaFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFacturaFinalActionPerformed(evt);
            }
        });

        cmbCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbCliente.setEnabled(false);

        cmbFacturaInicial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbFacturaInicial.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rbtTodo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbtSeleccion))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dchFechaFinal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dchFechaInicial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel1)
                    .addComponent(rbtFecha)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSeleccionArchivo))
                    .addComponent(rbtCliente)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnGenerarReporte, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtNroFactura)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cmbFacturaFinal, 0, 211, Short.MAX_VALUE)
                                            .addComponent(cmbFacturaInicial, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeleccionArchivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtSeleccion)
                    .addComponent(rbtTodo))
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(dchFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addComponent(jLabel5))
                    .addComponent(dchFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtNroFactura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbFacturaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbFacturaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGenerarReporte)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtSeleccionActionPerformed
        habilitarCampos();
    }//GEN-LAST:event_rbtSeleccionActionPerformed

    private void rbtTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtTodoActionPerformed
        habilitarCampos();
    }//GEN-LAST:event_rbtTodoActionPerformed

    private void rbtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtFechaActionPerformed
        habilitarCampos();
    }//GEN-LAST:event_rbtFechaActionPerformed

    private void rbtNroFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtNroFacturaActionPerformed
        habilitarCampos();
    }//GEN-LAST:event_rbtNroFacturaActionPerformed

    private void rbtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtClienteActionPerformed
        habilitarCampos();
    }//GEN-LAST:event_rbtClienteActionPerformed

    private void btnGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReporteActionPerformed
        if (txtArchivo.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Debe indicar un nombre de archivo");
            return;
        }
        try {
            String archivo = txtArchivo.getText() + ".pdf";
            String sql = "SELECT factura.idFactura, factura.idCliente, "
                    + "CONCAT(nombres, ' ', apellidos) AS nomCliente, " 
                    + "fecha, idLinea, idProducto, descripcion, precio, cantidad, "
                    + "precio * cantidad AS valor FROM factura "
                    + "INNER JOIN clientes ON factura.idCliente = clientes.idCliente " 
                    + "INNER JOIN detallefactura ON factura.idFactura = detallefactura.idFactura";
            
            String filtro = "";
            if (rbtTodo.isSelected()) {
                filtro = "";
            } else {
                if (rbtCliente.isSelected()) {
                    if (cmbCliente.getSelectedIndex() == 0) {
                        JOptionPane.showMessageDialog(rootPane, 
                                "Debe seleccionar un cliente");
                        return;                        
                    }
                    filtro = " WHERE factura.idCliente = '" 
                            + ((Opcion)cmbCliente.getSelectedItem()).getValor() + "'";
                }
                if (rbtNroFactura.isSelected()) {
                    if (cmbFacturaInicial.getSelectedIndex() == 0) {
                        JOptionPane.showMessageDialog(rootPane, 
                                "Debe seleccionar una factura inicial");
                        cmbFacturaInicial.requestFocusInWindow();
                        return;   
                    }
                    if (cmbFacturaFinal.getSelectedIndex() == 0) {
                        JOptionPane.showMessageDialog(rootPane, 
                                "Debe seleccionar una factura final");
                        cmbFacturaFinal.requestFocusInWindow();
                        return;                        
                    }
                    filtro = " WHERE factura.idFactura BETWEEN " 
                            + ((Opcion)cmbFacturaInicial.getSelectedItem()).getValor() + " AND "
                            + ((Opcion)cmbFacturaFinal.getSelectedItem()).getValor();
                }
                
                if (rbtFecha.isSelected()) {
                    if (dchFechaInicial.getDate() == null) {
                        JOptionPane.showMessageDialog(rootPane, 
                                "Debe seleccionar una fecha inicial");
                        dchFechaInicial.requestFocusInWindow();
                        return;                        
                    }
                    if (dchFechaFinal.getDate() == null) {
                        JOptionPane.showMessageDialog(rootPane, 
                                "Debe seleccionar una fecha final");
                        dchFechaFinal.requestFocusInWindow();
                        return;                        
                    }
                    filtro = " WHERE fecha BETWEEN '" 
                            + Utilidades.formatDate(dchFechaInicial.getDate()) + "' AND '"
                            + Utilidades.formatDate(dchFechaFinal.getDate()) 
                            + "' ORDER BY fecha";
                }
                
            }
            sql += filtro;
            Reporte.reporteFacturas(archivo, misDatos.getConsulta(sql));
            JOptionPane.showMessageDialog(rootPane, "Reporte Generado");
        } catch (Exception ex) {
            Logger.getLogger(frmReporteFacturas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGenerarReporteActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        try {
            //Cargamos los clientes
            Opcion opcion;
            opcion = new Opcion("NA", "Seleccione un cliente...");
            cmbCliente.addItem(opcion);
            ResultSet rs = misDatos.getClientes();
            
            while (rs.next()) {
                opcion = new Opcion(
                        rs.getString("idCliente"),
                        rs.getString("nombres") + " "
                                + rs.getString("apellidos"));
                
                cmbCliente.addItem(opcion);
            }
            
            //Cargamos las facturas
            opcion = new Opcion("NA", "Seleccione una factura...");
            cmbFacturaInicial.addItem(opcion);
            cmbFacturaFinal.addItem(opcion);
            rs = misDatos.getConsulta("select * from factura");
            
            while (rs.next()) {
                opcion = new Opcion(
                        rs.getString("idFactura"),
                        rs.getString("idFactura"));
                
                cmbFacturaInicial.addItem(opcion);
                cmbFacturaFinal.addItem(opcion);
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmReporteFacturas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formInternalFrameOpened

    private void cmbFacturaFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFacturaFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbFacturaFinalActionPerformed

    private void btnSeleccionArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionArchivoActionPerformed
        frmSelectorArchivo miSelector = new frmSelectorArchivo(null, closable);

        //Centramos el formulario en la pantalla (no en ventana)
        miSelector.setLocationRelativeTo(null);
        miSelector.setVisible(true);
        //Capturamos el archivo seleccionado
        String respuesta = miSelector.getArchivo();
        if (respuesta.equals("")) {
            return;
        }
        //Asignamos al cuadro el texto devuelto
        txtArchivo.setText(respuesta);        
    }//GEN-LAST:event_btnSeleccionArchivoActionPerformed

    private void habilitarCampos() {
        if (rbtTodo.isSelected()) {
            rbtFecha.setEnabled(false);
            rbtNroFactura.setEnabled(false);
            rbtCliente.setEnabled(false);
            dchFechaInicial.setEnabled(false);
            dchFechaFinal.setEnabled(false);
            cmbFacturaFinal.setEnabled(false);
            cmbFacturaFinal.setEnabled(false);
            cmbCliente.setEnabled(false);
        } else {
            rbtFecha.setEnabled(true);
            rbtNroFactura.setEnabled(true);
            rbtCliente.setEnabled(true);
            if (rbtFecha.isSelected()) {
                dchFechaInicial.setEnabled(true);
                dchFechaFinal.setEnabled(true);
            } else {
                dchFechaInicial.setEnabled(false);
                dchFechaFinal.setEnabled(false);
            }
            if (rbtNroFactura.isSelected()) {
                cmbFacturaInicial.setEnabled(true);
                cmbFacturaFinal.setEnabled(true);
            } else {
                cmbFacturaInicial.setEnabled(false);
                cmbFacturaFinal.setEnabled(false);
            }
            if (rbtCliente.isSelected()) {
                cmbCliente.setEnabled(true);
            } else {
                cmbCliente.setEnabled(false);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgrFiltro;
    private javax.swing.ButtonGroup bgrTipo;
    private javax.swing.JButton btnGenerarReporte;
    private javax.swing.JButton btnSeleccionArchivo;
    public javax.swing.JComboBox cmbCliente;
    public javax.swing.JComboBox cmbFacturaFinal;
    public javax.swing.JComboBox cmbFacturaInicial;
    private com.toedter.calendar.JDateChooser dchFechaFinal;
    private com.toedter.calendar.JDateChooser dchFechaInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JRadioButton rbtCliente;
    private javax.swing.JRadioButton rbtFecha;
    private javax.swing.JRadioButton rbtNroFactura;
    private javax.swing.JRadioButton rbtSeleccion;
    private javax.swing.JRadioButton rbtTodo;
    private javax.swing.JTextField txtArchivo;
    // End of variables declaration//GEN-END:variables
}
